apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi # Logical label; EFS is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # Multiple pods across nodes can use it
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0334584a460b87f14::fsap-0d48f30969fbbe075
