apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: nikhilpantam79@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            class: alb
            ingressTemplate:
              metadata:
                annotations:
                  alb.ingress.kubernetes.io/scheme: internet-facing
                  alb.ingress.kubernetes.io/target-type: ip
                  alb.ingress.kubernetes.io/ssl-redirect: "false"
                  # CRITICAL: Use same group name as main ingress
                  alb.ingress.kubernetes.io/group.name: credential-app
                  # CRITICAL: Give challenge solver higher priority
                  alb.ingress.kubernetes.io/group.order: "1"
