# k8s/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credential-app-ingress
  namespace: kube-credential-ns
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: your-temporary-placeholder.com # Replace with your actual domain or sslip.io address
      http:
        paths:
          # Frontend is the default
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          # Backend paths
          - path: /issue
            pathType: Prefix
            backend:
              service:
                name: issuance-service
                port:
                  number: 8081
          - path: /verify
            pathType: Prefix
            backend:
              service:
                name: verification-service
                port:
                  number: 8082
