apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: credential-app-ingress
  namespace: kube-credential-ns
  annotations:
    # cert-manager will issue the TLS certificate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # AWS Load Balancer Controller annotations
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: app.35.171.113.187.sslip.io
      http:
        paths:
          # Verification service route
          - path: /verify
            pathType: Prefix
            backend:
              service:
                name: verification-service
                port:
                  number: 8082
          # Issuance service route
          - path: /issue
            pathType: Prefix
            backend:
              service:
                name: issuance-service
                port:
                  number: 8081
          # Default route for the frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
  tls:
    - hosts:
        - app.35.171.113.187.sslip.io
      secretName: credential-app-tls
